services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        # defines the scalar arguments once and apply them to any service defined/created in this file

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Common\CoreBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Doctrine,Form,Migrations,Pagination,Presentation,Tests}'

    Common\CoreBundle\Manager\Firm\BalanceManager\:
        resource: '../../Manager/Firm/BalanceManager/*'
        tags:
            - { name: 'balance.activator' }

    Common\CoreBundle\Doctrine\EventSubscriber\:
        resource: '../../Doctrine/EventSubscriber/*'
        tags:
            - { name: 'doctrine.event_subscriber' }

    Common\CoreBundle\Security\Voter\:
        resource: '../../Security/Voter/*'
        tags:
            - { name: 'security.voter' }

    Common\CoreBundle\Manager\Szamlazzhu\CreateInvoice:
        arguments:
            $pdfBasePath: '%kernel.project_dir%/web/uploads'
