twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
    globals:
        # Google analytics code
        ga_tracking: UA-109725474-1
